### ISSUE TITLE
bibo:edition, bibo:issue

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/OLD-VIVO-languages#13]
bibo:edition und bibo:issue werden beide als Ausgabe übersetzt. Laut der VIVO-Definition: 

- bibo:issue
"Bibo has the domain of bibo:issue as the class Issue, but an example on their site uses it with Article, referring to the issue number "4""

- bibo:edition
"The name defining a special edition of a document. Normally its a literal value composed of a version number and words."
Nach RDA wird die Information, die auf die veränderte, spezielle, überarbeitete Version/Fassung eines Dokumentes hinweist, in dem Ausgabevermerk erfasst. Aus diesem Grund würde ich vorschlagen bibo:edition als Ausgabe@de-DE und bibo:issue als Heftnummer@de-De zu übersetzen.

**Comment by tawahle** [comment]
Da es auch eine Klasse bibo:Issue gibt, die bereits als "Ausgabe"@de-DE übersetzt wird, würde ich vorschlagen die Property bibo:edition als "Ausgabebezeichnung"@de-DE zu übersetzen.

**Comment by grahamtriggs** [comment]
This issue was moved to grahamtriggs/scratchpad#5
