### ISSUE TITLE
obo:ERO_0000225

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/OLD-VIVO-languages#16]
obo:ERO_0000225 wird hier als "Rolle des Erziehers übersetzt". Die Übersetzung passt aus meiner Sicht nicht in den Kontext. Aus der Definition in VIVO: "A role inhering in a person or organization that is realized when the bearer participates in providing education to a student or group of students." Der Beispiel in VIVO: "A teacher". 
Vorschlag: "Rolle des/der Lehrenden"@de

**Comment by grahamtriggs** [comment]
This issue was moved to grahamtriggs/scratchpad#4
