### ISSUE TITLE
hasProceedings

### ISSUE THREAD

**Issue by tawahle** [VIVO-DE/OLD-VIVO-languages#23]
http://vivoweb.org/ontology/core#hasProceedings rdfs:label "Tagungsberichte"@de würde ich übersetzen als "hatTagungsband"@de oder "Tagungsbände".

**Comment by tawahle** [comment]
"Tagungsband"@de käme auch in Frage.

**Comment by grahamtriggs** [comment]
This issue was moved to grahamtriggs/scratchpad#2
