### ISSUE TITLE
Textbaustein "Keine Publikationen" im publication graph

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/OLD-VIVO-languages#5]
Zeile 565ff. in vivo-1.6/de_DE/themes/wilma/i18n/all_de_DE.properties:

```
view = Ansicht
entity_comp_error_text1 = Diese Organisation hat weder Unterorganisationen noch Personen
entity_comp_error_text2 = im System.
entity_comp_error_text3 = Bitte besuchen Sie das Portal,
entity_comp_error_text4 = um einen vollständigeren Überblick zu erhalten.
profile_page = Profilseite
```

Resultiert (nach Ergänzung eines fehlenden "mit") in:

> Diese Organisation hat weder Unterorganisationen noch Personen mit publications im System. Bitte besuchen Sie das Portal, Finance, Accounting, Controlling & Taxation (FACT) Profilseite um einen vollständigeren Überblick zu erhalten.

"Profilseite" ist verlinkt.

Beispiel: https://vivo.tib.eu/demo/vis/publication-graph/?uri=http%3A%2F%2F192.168.56.10%3A8080%2Fvivo%2Findividual%2Fn1046

Wie stellen wir das um?

**Comment by hauschke** [comment]
Vorschlag:
> view = Ansicht
> entity_comp_error_text1 = Für diese Organisation sin weder Unterorganisationen noch Personen mit
> entity_comp_error_text2 = gespeichert.
> entity_comp_error_text3 = Bitte besuchen Sie das Profil 
> entity_comp_error_text4 = für einen vollständigeren Überblick.
> profile_page = 

profile_page würde entfallen, um auf die Bildung des Kompositums verzichten zu können.

**Comment by grahamtriggs** [comment]
This issue was moved to grahamtriggs/scratchpad#8
