### ISSUE TITLE
Singular & Plural für Klassen

### ISSUE THREAD

**Issue by hauschke** [VIVO-DE/OLD-VIVO-languages#8]
https://groups.google.com/forum/#!searchin/vivo-tech/plural|sort:relevance/vivo-tech/mK0bJ-D6qO8/6gwuI_KSBQAJ

Für die Klassen werden in vielen Fällen Singular und Plural notwendig, falls die vorgeschlagene Lösung in VIVO implementiert wird. Zitat:

> An alternative solution might be to add the plurals to the internationalization file all_de_DE.properties with a predicable string name. Like Buch_plural == Bücher, then in lib-home-page.ftl change the logic to look for the plural string in that file, something like ${i18n().${class.name}}. Disclaimer: I’m not sure if this is the proper way to nest freemarker statements, I’m not sure if it works.

**Comment by grahamtriggs** [comment]
This issue was moved to grahamtriggs/scratchpad#6
